apiVersion: v1
kind: Pod
metadata:
  name: app-pod
  labels:
    app: app-pod

spec:
  containers:
    - name: app-container
      image: kodekloud/simple-webapp-color
      ports:
        - containerPort: 8080
      envFrom:
        - configMapRef:
            name: app-config
